### ISSUE TITLE
Backend: API to calculate Return-To-Work score

### ISSUE THREAD

**Issue by dhanashri-dotcom** [dhanashri-dotcom/CommonAssessmentToolUI#7]
Task: Identify an API that calculates the new Return-To-Work score based on the updated client information. Create placeholder API calls for frontend development if the backend APIs don’t exist yet.
Description: Inform the backend team about the api. Add temporary placeholder functions to simulate API interactions to calculate the Return-To-Work score using updated client information and store the new score in the database.
Acceptance Criteria:
- Placeholder functions are created and can be swapped with real APIs once available.
- The API successfully calculates and returns the new score based on client data.

**Comment by bonicim** [comment]
Currently the API is calling a real API hosted in AWS. We want the API to call a placeholder "API" that you have built or modified. As a bonus, explore how to configure the frontend to use the placeholder API or real API at "runtime" (hint: environment variables).

**Comment by mereluo** [comment]
**Updated:**

**Task 1: Design API Endpoint**
**Description:** Design the API structure, including the endpoint URLs, HTTP methods, and the request/response body. Ensure the API conforms the REST standards.
**Acceptance Criteria:**
- The API endpoint is defined (e.g., `/api/v1/return-to-work-score`).
- HTTP method (`POST`) is decided.
- Request and response body structure is clearly outlined.

**Task2: Create Placeholder Functions for API Simulation**
**Description:** Create placeholder API functions to simulate the Return-To-Work score calculation. These functions will return a hardcoded or calculated score until the real API is available.
**Acceptance Criteria:**
- Placeholder API function is created and running locally.
- Extract relevant client data from the frontend in a structured format (based on the API input design from Task 1). For instance, the frontend might send:
```
{
  "clientId": "12345",
  "updatedClientInfo": {
    "educationLevel": "Bachelor's",
    "employmentStatus": "Part-time",
    "medicalCondition": "Stable"
  }
}
```
- The API returns a fixed score (e.g., 85) or a calculated score in the response body defined in Task 1 for testing purposes.  For instance, the `res.json` might have a structure:
```
const result = {
    probability: 85,
    interventions: [
      "Attend job skills workshop: increased by 2.5%",
      "Participate in language improvement classes: increased by 3%",
      "Join professional networking events: increased by 2%"
    ]
  };
res.json(result);
```
- The API is ready for frontend integration with the placeholder function.

**Comment by mereluo** [comment]
![image](https://github.com/user-attachments/assets/554ca281-f9a9-450e-afde-d2e8b5f6d2fb)
